server:
  name: go-firestore-rest-api
  port: 8080

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: request
  response: response
  size: size

credentials: '
  {
    "type": "service_account",
    "project_id": "go-firestore-6f8a0",
    "private_key_id": "3361cca40dd4dfcbfd6940b60cd448a9146f5200",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC14ywkwubUtllv\nVXKKSMTuSgeqO75IKZgKNKCKVngkSklScNSZQMyEDoD3OBCl+NAadK0S71TMg1uX\np3VmyKJWNZzZvI/3/O+hyM1c6vkS1JgQl5Ep1gD+1hvgHaFiAVQEzvjKJHrGVxXh\n9m2dq+ZR4j3dY5PC91zzNaUClzaxafu+loQwXMf3PWcPa8X4njLaxdJl+jLXSe6H\n3sJtdUyPAyVSKnrWzVGQO7HXnKLuEJNL3Gj9ewCGiIJdEtaXtpQkYtobokbHWs0/\nL5AaZIZRgJSzo/WjkAxgpnn5OaRtZ477TYxiHyMe595ZHBFKUwmUMRu/1esR/cAS\nLy2NeKp5AgMBAAECggEABgVmrTLchFci/8oC2CwPhNnjhhGjO21REKlsVRgGsyDY\na4e7qfUYsBhw0X5EItJpRS7umc1db8W7bvpGqyfiI9tzfUu+MlXnsuHcVoKayzJJ\ndGcoEYv5jXYWByXD9WQY3W3ik4KAo/c3DLtlJo6NudE0/hKxTgd1RsHUXBEYaOgM\nVZbjCysENynXjJlbA6sLGiZ/W66hpdRAEtkVLA6aUxU36OhN+n8kFaWyZn6fToiH\nYNGv9AJQs/mQWBAqSrWLFsMWD2V8l7YznWdEIUNKKdtXA9UaGj01UjMzS27U7nmI\nSRlspsPyut0exZ9h1zgDTtfcLIYYq7BGvZs4X8kLeQKBgQD4N35zpWdKXOHKycRf\nz5QZ/1zl3wR1JCZlAxCY1dHjAtO+8OH4ytfCi2NzVvnBblVdHIL5P8R0DDDnZN2n\nDkg2r0tarEz34MpE/3n+DThAYUqLgyqNjfDGDqxQBfhX8Sq78zh/MwXHbsrt7kEK\ncoYig8pfH38+43KAtbtq+GZAXQKBgQC7lzvcndTvvwyGkS9SNzFM0CEPq3tlQ4X1\n1KwtHadC4X5mxzWkOyUaV6Ws/Ih47tjmI+VK9ga0U9fGM4948od2u3U13T6JHCkg\nR2StirvjJ8nYb2nHgX7+pXWXjlm9nFZ1YiZtRa8ou/1btZcQNka75Kmj+mY5v2UG\nJSyMtwGgzQKBgAr1+GGG9k60V0wrKL7KXdHgEuwbswixNfjT79Gv73rEzzDpVjE0\nU97FZPjc6F6ATsizz5zOEhDF0QsGyzrrSIkRqJQyc5umk4gEeBCd6NP+99m9Sw3B\nLNayIy3Nda/8eFSgYuhLCoBKBjAHi1u4vu+bPj6BF49hX9cLL2GD4pAJAoGAMHOE\nS5wcZnvi4VLYdRS6UAulrmVtLp99FxyCB/kTvWt+eU9UpIF+OMqQiRiEqy+NqAt3\naqAW5TaOkau5j9Scdmc+g9YME9/JI4QtFcGye55IPPWxzYy930mfELD8rsOVdSYP\npMON1SiQ7MH/LXnHVTpfMnI3Ow0bK7YoRoPyELUCgYEAxJRcLS58d5Qw0n9Njb+Z\n8OO7fQT3tt6ZPh+U5lHl27C+7Hp8f67zZaaTNdcXi3Cl4VRvZtiWqbEwykve4UYk\nh2PO/Zxk+zop5YyOXDWwW38Hm8HMwtWhBoeAyeescGr80nLwt6wNz94AqhIeu0SH\n4f7nRZMt56HhlF7J5ScEkxo=\n-----END PRIVATE KEY-----\n",
    "client_email": "firebase-adminsdk-l2qkf@go-firestore-6f8a0.iam.gserviceaccount.com",
    "client_id": "105402974299331807787",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-l2qkf%40go-firestore-6f8a0.iam.gserviceaccount.com"
  }'